# -*- coding: utf-8 -*-
"""CBSOT project 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nEhRFMwlw7pnXRSeuj_0lIqQkO3mq1xI
"""

!pip install datasets

from datasets import load_dataset

dataset=load_dataset("CShorten/ML-ArXiv-Papers",split="train")

dataset[0]

import pandas as pd

df=pd.DataFrame(dataset)
df

df.columns

df = df[['title','abstract']].copy()

df

df.shape

df = df.head(15000).copy()

df.shape

df.isnull().sum()

df["paper_text"]=df["title"]+" "+df["abstract"]

df[["paper_text"]].head()

type(df[["paper_text"]])

df[["paper_text"]].head()

print(df["paper_text"].iloc[0])

from sentence_transformers import SentenceTransformer

model=SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

print(type(model))

df["paper_text"] = df["paper_text"].str.replace("\n","",regex=False)
df["paper_text"] = df["paper_text"].str.strip()

sample_text=df["paper_text"].iloc[0]
sample_text

embedding=model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

embedding[:56]

sample_embedding=model.encode(df['paper_text'].head(5).to_list())

print(sample_embedding.shape)

from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[0].reshape(1,-1))
print(similarity)

similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[1].reshape(1,-1))
print(similarity)

for i in range(1,5):
  sim=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[i].reshape(1,-1))
  print(similarity)

"""Generate full embedding

"""

import os
import numpy as np
if os.path.exists("paper_embeddings.npy"):
  print("loading existing embeddings")
  embeddings=np.load("paper_embeddings.npy")
else:
  print("creating new embeddings")
  embeddings=model.encode(df["paper_text"].to_list(),batch_size=32,show_progress_bar=True)
  np.save("paper_embeddings.npy",embeddings)
  print("embeddings created successfully")

print(embedding.shape)
print(type(embedding))

print("Verifying embedding shape before faiss.normalize_L2:")
print(f"Embedding shape: {embedding.shape}")
print(f"Embedding type: {type(embedding)}")

embedding.dtype

!pip install faiss-cpu

import faiss

#faiss.normalize_L2(embedding)

#index= faiss.IndexFlatIP(384)

#index.add(embedding)

if os.path.exists("paper_faiss.index"):
  print("loading existing Faiss index")
  index=faiss.read_index("paper_faiss.index")
else:
  print("creating new Faiss index")
  faiss.normalize_L2(embedding)
  index=faiss.IndexFlatIP(384)
  index.add(embedding)
  faiss.write_index(index,"paper_faiss.index")
  print("Faiss index created successfully")

print(index.ntotal)

query="deep learning for medical image analysis"
query_embedding=model.encode([query])
query_embedding.shape

faiss.normalize_L2(query_embedding)

D,I=index.search(query_embedding,5)
print(D)
print(I)

print(df.iloc[10466]["title"])

print(df.iloc[12691]["title"])

def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  return D,I

D,I=search_paper("deep learning for medical image analysis")
print(D)
print(I)

def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Title:" ,df.iloc[idx]['title'])
    print("Similarity Score:" ,score)
    print("title", df.iloc[idx]['abstract'][:500])

search_paper("deep learning for medical image analysis")

!pip install transformers

!pip uninstall -y transformers tokenizers
!pip install transformers
from transformers import pipeline

"""KeyBERT Analysis"""

pip install keybert==0.8.5

from keybert import KeyBERT
kw_model = KeyBERT()

text= df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)
print (keywords)

keywords=kw_model.extract_keywords(text, keyphrase_ngram_range=(1, 3), stop_words=None)
print(keywords)

"""Named Entity Recognition (NER)

"""

from transformers import pipeline

# Initialize the NER pipeline
ner_pipeline = pipeline("ner", model="dslim/bert-base-NER")
print("NER pipeline initialized successfully.")

sample_title_for_ner = df.iloc[10466]["title"]
print("--- Sample Title ---")
print(sample_title_for_ner)

# Perform NER on the title
ner_results_title = ner_pipeline(sample_title_for_ner)

print("\n--- NER Results for Title ---")
if ner_results_title:
    for entity in ner_results_title:
        print(f"Entity: {entity['word']}, Type: {entity['entity']}, Score: {entity['score']:.4f}")
else:
    print("No named entities found in the title.")

from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import faiss

embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# Define the summarization tokenizer and model (used for generating summaries)
summarization_tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
summarization_model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")

def search_paper(query, k=5):
    query_embedding = embedding_model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)
    return D, I

def summarizer_search(query, k=5):
    D, I = search_paper(query, k)
    for score, idx in zip(D[0], I[0]):
        paper_title = df.iloc[idx]['title']
        paper_abstract = df.iloc[idx]['abstract']

        # Generate summary for the abstract using the summarization model
        inputs = summarization_tokenizer([paper_abstract], max_length=1024, return_tensors='pt', truncation=True)
        summary_ids = summarization_model.generate(
            inputs['input_ids'],
            num_beams=4,
            max_length=150,
            min_length=30,
            early_stopping=True
        )
        generated_summary = summarization_tokenizer.decode(summary_ids[0], skip_special_tokens=True)

        # Extract keywords using KeyBERT
        keywords = kw_model.extract_keywords(paper_abstract, keyphrase_ngram_range=(1, 3), stop_words='english')
        keywords_formatted = ", ".join([f'{word} ({score:.2f})' for word, score in keywords])

        # Perform NER on the abstract
        ner_results = ner_pipeline(paper_abstract)
        entities_formatted = []
        for entity in ner_results:
            # Filter out generic words or very short entities that are not very informative
            if len(entity['word'].strip()) > 1 and entity['entity'] not in ['O', 'MISC']:
                entities_formatted.append(f"{entity['word']} ({entity['entity']})")
        entities_formatted_str = ", ".join(list(set(entities_formatted))) # Use set to remove duplicates

        print(f"\n--- Search Result (Score: {score:.4f}) ")
        print(f"Title: {paper_title}")
        print(f"Abstract: {paper_abstract[:500]}")
        print(f"Summary: {generated_summary}")
        print(f"Keywords: {keywords_formatted}")
        print(f"Named Entities: {entities_formatted_str if entities_formatted_str else 'None found'}")

summarizer_search("deep learning for medical image analysis", k=3)

pip install langchain-community langchain-core

from langchain_core.tools import tool

@tool
def search_paper(query:str)-> str:
  "Search research paper from ther faiss database and return the most relevant result"

pip install langchain-community langchain-core langchain-huggingface

from langchain_huggingface import HuggingFacePipeline

llm=HuggingFacePipeline( pipeline=summarization_model)

llm